'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")>  _
Partial Friend NotInheritable Class SEI_GEST
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As SEI_GEST = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New SEI_GEST()),SEI_GEST)
    
    Public Shared ReadOnly Property [Default]() As SEI_GEST
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("150")>  _
    Public ReadOnly Property ITEM_FORMTYPEEX() As String
        Get
            Return CType(Me("ITEM_FORMTYPEEX"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("134")>  _
    Public ReadOnly Property BP_FORMTYPEEX() As String
        Get
            Return CType(Me("BP_FORMTYPEEX"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public ReadOnly Property BTN_OK_ID() As String
        Get
            Return CType(Me("BTN_OK_ID"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SEI_UNODE50_AutorizacionPr")>  _
    Public ReadOnly Property MENU_AutorizacionPr() As String
        Get
            Return CType(Me("MENU_AutorizacionPr"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SEI_UNODE50_AutorizacionCl")>  _
    Public ReadOnly Property MENU_AutorizacionCl() As String
        Get
            Return CType(Me("MENU_AutorizacionCl"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SEI_UNODE50_AutorizacionA")>  _
    Public ReadOnly Property MENU_AutorizacionA() As String
        Get
            Return CType(Me("MENU_AutorizacionA"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SEI_UNODE50_AutorizacionCl")>  _
    Public ReadOnly Property GESTIONIC_FORMID() As String
        Get
            Return CType(Me("GESTIONIC_FORMID"),String)
        End Get
    End Property
End Class
